# Generated by Django 5.0.1 on 2024-02-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_socialpost_shared_body_socialpost_shared_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shared_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
